apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apigateway-to-logic
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /analyse/sentence
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - localhost
      secretName: ingress-tls
  rules:
    - host: localhost
      http:
        paths:
          - path: /api/polarity
            pathType: Exact
            backend:
              service:
                name: logic-api-service
                port:
                  number: 5000
