apiVersion: apps/v1
kind: Deployment
metadata:
  name: logic-api
  labels:
    app: logic-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: logic-api
  template:
    metadata:
      labels:
        app: logic-api
    spec:
      containers:
        - image: khalil123456/logic-api:submission
          imagePullPolicy: Always
          name: logic-api
          ports:
            - containerPort: 5000
          env:
            - name: NLTK_DATA
              value: /usr/local/share/nltk_data
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 3
            periodSeconds: 3