apiVersion: apps/v1
kind: Deployment
metadata:
  name: logic-api-v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: logic-api
      version: v1
  template:
    metadata:
      labels:
        app: logic-api
        version: v1
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/connect-service: "logic-api"
        consul.hashicorp.com/service-tags: "version=v1"
    spec:
      containers:
        - name: logic-api
          image: khalil123456/logic-api:submission
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: NLTK_DATA
              value: /usr/local/share/nltk_data
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 3
            periodSeconds: 3
